### ISSUE TITLE
How to use with Java

### ISSUE THREAD

**Issue by simPod** [rmind/liblpm#10]
Hi, in README, there's

> Additionally, bindings are available for Lua and Java. There is a specification to build an RPM package.

Can you please guide me a little how to use within java? Thanks!

**Comment by rmind** [comment]
I added some information, but basically:
* Install JDK/JRE (8.x works, no idea about the other versions):
  * E.g. on Debian: `sudo apt-get install -y openjdk-8-jre-headless openjdk-8-jdk-headless`
* Set the `JAVA_HOME` according to your environment and build the JAR:
  * `cd liblpm/src/jni && JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 make test`
* The above will produce `liblpm.jar` and now you are in the Java land.

**Comment by simPod** [comment]
Thanks for help!
