### ISSUE TITLE
liblpm for fast high volume traffic

### ISSUE THREAD

**Issue by tinajohnson** [rmind/liblpm#7]
Is this library meant for or does it work with fast high volume traffic? The project we are working on uses DPDK and Flowscope (https://github.com/emmericp/FlowScope) for fast packet processing. Have you guys ever had a chance to test the performance of this library with fast high volume traffic?

Appreciate your help.

**Comment by rmind** [comment]
If serving multi-gigabit traffic across the UK [1] counts as "fast high volume traffic", then yes. :)  This library is also used in the NPF packet filter [2].

[1] https://www.bbc.co.uk/blogs/internet/entries/8c6c2414-df7a-4ad7-bd2e-dbe481da3633
[2] https://github.com/rmind/npf

**Comment by tinajohnson** [comment]
Got it, thank you!
